### PR TITLE
Fix for when an API returns an empty body, but content-type is JSON

### PR DESCRIPTION
**Pull request by Christian-Athom**

### CODE REVIEW

**Review by tjallingt — APPROVED** [review]

**Review by RobinBol — APPROVED** [review]
Looks good! I thought I saw a fix for this exact issue a while back, not sure where though.. :P (@WeeJeWel didn't you experience this issue somewhere?)

**Comment by WeeJeWel** [comment]
I don't think this is the right place. It means the API is broken, and should be overloaded in the app's OAuth2Client.

**Comment by Christian-Athom** [comment]
The problem with that is that in the app you cannot know if the response was 20x and the return body was empty, or that the error wan genuine. This is because the .json() call on the respons throws when the body is an empty string.

**Comment by WeeJeWel** [comment]
Still, you can overload `onHandleResponse` in your app.

Which API is this, by the way?

**Comment by Christian-Athom** [comment]
Honeywell Lyric Api

**Comment by WeeJeWel** [comment]
OK. Please fix it there, I want to to keep this module W3-spec compliant and not introduce hacks.

**Comment by WeeJeWel** [comment]
FYI They should not return the header, and a `204` status code.

**Pull request closed without merging**
